// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04Ds2rIx5il5ahgih1cja-L1TTVAXqHw',
    appId: '1:530384740832:web:0f8e7eceb36eb04f204b85',
    messagingSenderId: '530384740832',
    projectId: 'jerritomomo',
    authDomain: 'jerritomomo.firebaseapp.com',
    storageBucket: 'jerritomomo.appspot.com',
    measurementId: 'G-BEFV9P6MYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkPEIApIHTat-j_1Gt-6mZdaw9laZtaeA',
    appId: '1:530384740832:android:61250430be45a78e204b85',
    messagingSenderId: '530384740832',
    projectId: 'jerritomomo',
    storageBucket: 'jerritomomo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFCQu-Nz3b62HskK6JcCgSRK7d_XGScPI',
    appId: '1:530384740832:ios:4dd96dc99e58d7c6204b85',
    messagingSenderId: '530384740832',
    projectId: 'jerritomomo',
    storageBucket: 'jerritomomo.appspot.com',
    iosClientId: '530384740832-orbb7dtnp0ckbn0ppqo3uu7tr0iq8oub.apps.googleusercontent.com',
    iosBundleId: 'com.example.momo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFCQu-Nz3b62HskK6JcCgSRK7d_XGScPI',
    appId: '1:530384740832:ios:4dd96dc99e58d7c6204b85',
    messagingSenderId: '530384740832',
    projectId: 'jerritomomo',
    storageBucket: 'jerritomomo.appspot.com',
    iosClientId: '530384740832-orbb7dtnp0ckbn0ppqo3uu7tr0iq8oub.apps.googleusercontent.com',
    iosBundleId: 'com.example.momo',
  );
}
