// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa9j8DcUmMJ1mWk8zQ83jOANwpJ20ilp8',
    appId: '1:721464346945:web:584e197543b84b993079c0',
    messagingSenderId: '721464346945',
    projectId: 'momo-b71fd',
    authDomain: 'momo-b71fd.firebaseapp.com',
    storageBucket: 'momo-b71fd.appspot.com',
    measurementId: 'G-K2PB7SQ653',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBeG_FQrTcKH3nCzJE9bZm0IvR7IyaV4',
    appId: '1:721464346945:android:425f0969f25a7bbd3079c0',
    messagingSenderId: '721464346945',
    projectId: 'momo-b71fd',
    storageBucket: 'momo-b71fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZeMtkuKXpbFg6mfBxjXB6msptEdDcDlw',
    appId: '1:721464346945:ios:a255caeeabf800223079c0',
    messagingSenderId: '721464346945',
    projectId: 'momo-b71fd',
    storageBucket: 'momo-b71fd.appspot.com',
    iosClientId: '721464346945-sdb5hdigo8bimtmkgnb85t6es6l411b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.momo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZeMtkuKXpbFg6mfBxjXB6msptEdDcDlw',
    appId: '1:721464346945:ios:a255caeeabf800223079c0',
    messagingSenderId: '721464346945',
    projectId: 'momo-b71fd',
    storageBucket: 'momo-b71fd.appspot.com',
    iosClientId: '721464346945-sdb5hdigo8bimtmkgnb85t6es6l411b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.momo',
  );
}
